package main

import (
	"bufio"
	"fmt"
	"io"
	"maps"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync/atomic"
	"time"
)

// releaseEntry is one index file that must be listed in the Release checksums.
type releaseEntry struct {
	Rel string // path relative to dists/<codename>/, always forward slashes
	Abs string
}

// distsResult is what generateDists produced, and what Release must describe.
type distsResult struct {
	Root          string // <dest>/dists/<codename>
	Architectures []string
	Entries       []releaseEntry
}

// writeField appends "Name: value" only when value is set, so empty fields do
// not end up in the index.
func writeField(b *strings.Builder, name, value string) {
	if value == "" {
		return
	}
	b.WriteString(name)
	b.WriteString(": ")
	b.WriteString(value)
	b.WriteString("\n")
}

// writeStanza renders one package in Debian control format. Only standard
// fields are emitted: the mirror URL is kept out of the published index and
// recorded in the manifest instead.
func writeStanza(b *strings.Builder, p *PackageDeb) {
	writeField(b, "Package", p.Package)
	writeField(b, "Version", p.Version)
	writeField(b, "Installed-Size", p.InstalledSize)
	writeField(b, "Maintainer", p.Maintainer)
	writeField(b, "Architecture", p.Arch)
	writeField(b, "Pre-Depends", p.Pre_Depends)
	writeField(b, "Depends", p.Depends)
	writeField(b, "Provides", p.Provides)
	writeField(b, "Breaks", p.Breaks)
	writeField(b, "Homepage", p.Homepage)
	writeField(b, "Description", p.Description)
	writeField(b, "Tag", p.Tag)
	writeField(b, "Section", p.Section)
	writeField(b, "Priority", p.Priority)
	writeField(b, "Filename", p.Filename)
	writeField(b, "Size", p.Size)
	writeField(b, "MD5sum", p.MD5sum)
	writeField(b, "SHA256", p.SHA256)
	b.WriteString("\n")
}

// generateDists writes dists/<codename>/main/binary-<arch>/Packages plus its
// .gz and .xz variants, one independent file per architecture.
func generateDists(config *Config, selected map[string][]*PackageDeb) (*distsResult, error) {
	result := &distsResult{
		Root: filepath.Join(config.Destination.Path, "dists", DestinationDistsName),
	}

	for _, arch := range config.Destination.Arch {
		packages := selected[arch]
		if len(packages) == 0 {
			continue
		}

		// A fresh builder per architecture: reusing one leaks every previous
		// architecture's packages into this index.
		var b strings.Builder
		for _, pkg := range packages {
			// Raw is only set on demand, where dropping a field apt acts on
			// would let it plan an install dpkg then refuses.
			if pkg.Raw != "" {
				b.WriteString(pkg.Raw)
				continue
			}
			writeStanza(&b, pkg)
		}

		relDir := path.Join(DestinationComponent, "binary-"+arch)
		dir := filepath.Join(result.Root, DestinationComponent, "binary-"+arch)
		packagesPath := filepath.Join(dir, "Packages")

		err := writeFileAtomic(packagesPath, func(w io.Writer) error {
			_, err := io.WriteString(w, b.String())
			return err
		})
		if err != nil {
			return nil, fmt.Errorf("%s %s: %v", _t("error c P"), packagesPath, err)
		}

		// On demand the index is the whole archive - around 50 MB for a Debian
		// suite - and the pure Go xz writer needs a minute or more for that,
		// for a variant apt is happy to do without as long as Release does not
		// promise it.
		produced, err := compressIndex(packagesPath, !config.Settings.OnDemand)
		if err != nil {
			return nil, fmt.Errorf("%s %s: %v", _t("error w P"), packagesPath, err)
		}

		for _, name := range append([]string{"Packages"}, produced...) {
			result.Entries = append(result.Entries, releaseEntry{
				Rel: path.Join(relDir, name),
				Abs: filepath.Join(dir, name),
			})
		}
		result.Architectures = append(result.Architectures, arch)
	}

	if len(result.Entries) == 0 {
		return nil, fmt.Errorf("%s", _t("no p selected"))
	}
	return result, nil
}

// generateRelease writes dists/<codename>/Release with the checksums apt needs.
//
// It is deliberately not called InRelease: that name is reserved for an inline
// OpenPGP-signed document, and tinyrepo does not sign. Consume the repository
// with "deb [trusted=yes] ...".
func generateRelease(result *distsResult) error {
	var b strings.Builder

	b.WriteString("Origin: Tinyrepo\n")
	b.WriteString("Label: Tinyrepo\n")
	b.WriteString("Suite: " + DestinationDistsName + "\n")
	b.WriteString("Codename: " + DestinationDistsName + "\n")
	b.WriteString("Architectures: " + strings.Join(result.Architectures, " ") + "\n")
	b.WriteString("Components: " + DestinationComponent + "\n")
	b.WriteString("Date: " + time.Now().UTC().Format(time.RFC1123) + "\n")
	b.WriteString("Description: Local repository generated by tinyrepo\n")

	md5Lines := &strings.Builder{}
	sha256Lines := &strings.Builder{}

	for _, entry := range result.Entries {
		md5Hex, sha256Hex, size, err := hashFile(entry.Abs)
		if err != nil {
			return fmt.Errorf("%s %s: %v", _t("err g release"), entry.Abs, err)
		}
		fmt.Fprintf(md5Lines, " %s %d %s\n", md5Hex, size, entry.Rel)
		fmt.Fprintf(sha256Lines, " %s %d %s\n", sha256Hex, size, entry.Rel)
	}

	b.WriteString("MD5Sum:\n")
	b.WriteString(md5Lines.String())
	b.WriteString("SHA256:\n")
	b.WriteString(sha256Lines.String())

	releasePath := filepath.Join(result.Root, "Release")
	err := writeFileAtomic(releasePath, func(w io.Writer) error {
		_, err := io.WriteString(w, b.String())
		return err
	})
	if err != nil {
		return fmt.Errorf("%s %s: %v", _t("err g release"), releasePath, err)
	}

	logDebug(_t("downloaded"), releasePath)
	return nil
}

// manifestEntry is one .deb to fetch, with everything needed to verify it.
type manifestEntry struct {
	BaseURL  string
	PoolPath string
	Size     int64
	SHA256   string
}

// sourceURL is where this file is fetched from upstream.
func (e manifestEntry) sourceURL() string {
	return strings.TrimRight(e.BaseURL, "/") + "/" + strings.TrimLeft(e.PoolPath, "/")
}

// localPath is where it lives inside the destination repository. It is also,
// with a leading slash, the URL a client asks tinyrepo for - which is what lets
// the web server look a missing file straight up in the catalog.
//
// It can fail: PoolPath is the mirror's own Filename field, so it has to be
// checked rather than trusted. See safeJoin.
func (e manifestEntry) localPath(root string) (string, error) {
	return safeJoin(root, e.PoolPath)
}

// check is what a downloaded copy has to match.
func (e manifestEntry) check(config *Config) fileCheck {
	want := fileCheck{Size: e.Size}
	if config.Settings.VerifyChecksum {
		want.SHA256 = e.SHA256
	}
	return want
}

func manifestPath(config *Config) string {
	return filepath.Join(config.Destination.Path, ManifestDirName, ManifestFileName)
}

// writeManifest records where each selected Debian package must be downloaded
// from. Keeping this out of the published Packages file lets the index stay
// standard.
func writeManifest(config *Config, selected map[string][]*PackageDeb) error {
	var entries []manifestEntry

	for _, packages := range selected {
		for _, pkg := range packages {
			if pkg.Filename == "" {
				continue
			}
			size, _ := strconv.ParseInt(pkg.Size, 10, 64)
			entries = append(entries, manifestEntry{
				BaseURL:  pkg.FilenameUrl,
				PoolPath: pkg.Filename,
				Size:     size,
				SHA256:   pkg.SHA256,
			})
		}
	}
	return writeManifestEntries(config, entries)
}

// writeManifestEntries is the format-neutral half: it deduplicates by path,
// sorts for a stable file, and writes it atomically.
func writeManifestEntries(config *Config, entries []manifestEntry) error {
	// The same file can be reached from more than one index: an
	// Architecture:all .deb appears in every architecture's Packages, and an
	// "any" package appears in every pacman repository database.
	unique := make(map[string]manifestEntry, len(entries))
	for _, entry := range entries {
		if entry.PoolPath == "" {
			continue
		}
		// Rejected here as well as where it is used, so a path that would be
		// written outside the repository never even reaches the manifest.
		if !safeRelPath(entry.PoolPath) {
			logError(_t("err unsafe path"), entry.PoolPath)
			continue
		}
		if _, exists := unique[entry.PoolPath]; !exists {
			unique[entry.PoolPath] = entry
		}
	}

	var b strings.Builder
	b.WriteString(ManifestHeader)

	for _, poolPath := range slices.Sorted(maps.Keys(unique)) {
		entry := unique[poolPath]
		fmt.Fprintf(&b, "%s\t%s\t%d\t%s\n", entry.BaseURL, entry.PoolPath, entry.Size, entry.SHA256)
	}

	return writeFileAtomic(manifestPath(config), func(w io.Writer) error {
		_, err := io.WriteString(w, b.String())
		return err
	})
}

func readManifest(path string) ([]manifestEntry, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var entries []manifestEntry
	scanner := bufio.NewScanner(file)

	for lineNo := 1; scanner.Scan(); lineNo++ {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Split(line, "\t")
		if len(fields) != 4 {
			return nil, fmt.Errorf("%s:%d: %s", path, lineNo, line)
		}

		size, err := strconv.ParseInt(fields[2], 10, 64)
		if err != nil {
			return nil, fmt.Errorf("%s:%d: %v", path, lineNo, err)
		}

		// A manifest is a file on disk that could have been edited, or written
		// by an older build that did not check.
		if !safeRelPath(fields[1]) {
			logErrorf("%s %s:%d: %s", _t("err unsafe path"), path, lineNo, fields[1])
			continue
		}

		entries = append(entries, manifestEntry{
			BaseURL:  fields[0],
			PoolPath: fields[1],
			Size:     size,
			SHA256:   fields[3],
		})
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

// downloadPool fetches every .deb listed in the manifest, in parallel, and
// verifies it against the checksum published in the upstream index.
func downloadPool(config *Config) error {
	entries, err := readManifest(manifestPath(config))
	if err != nil {
		return fmt.Errorf("%s %v", _t("err r manifest"), err)
	}
	if len(entries) == 0 {
		logError(_t("no p selected"))
		return nil
	}

	logDebugf("%s %d", _t("n downloads"), len(entries))

	var failed atomic.Int64
	tasks := make([]func(), 0, len(entries))

	for _, entry := range entries {
		tasks = append(tasks, func() {
			sourceURL := entry.sourceURL()

			dest, err := entry.localPath(config.Destination.Path)
			if err != nil {
				logErrorf("%s %s: %v", _t("err unsafe path"), entry.PoolPath, err)
				failed.Add(1)
				return
			}
			want := entry.check(config)

			if err := downloadFile(sourceURL, dest, want); err != nil {
				logErrorf("%s %s: %v", _t("error d"), sourceURL, err)
				failed.Add(1)
			}
		})
	}

	runConcurrent(config.Settings.MaxConcurrentDownloads, tasks)

	if n := failed.Load(); n > 0 {
		return fmt.Errorf("%s %d/%d", _t("d failed"), n, len(entries))
	}
	return nil
}
